import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getFunctions, httpsCallable } from "firebase/functions";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBDykfv5A9ERar5lRjts4uq5Yv9-y7gxwo",
  authDomain: "dwollatest.firebaseapp.com",
  projectId: "dwollatest",
  storageBucket: "dwollatest.appspot.com",
  messagingSenderId: "316179236172",
  appId: "1:316179236172:web:851d491a896c2548ef3be9",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const functions = getFunctions(app);
const createCustomer = httpsCallable(functions, "createCustomer");

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full flex flex-row items-center justify-center px-8 py-4 ">
        <h1 className="text-xl font-bold">My Dwolla Website</h1>
      </header>

      <main>
        <section className="w-full flex flex-col items-center justify-center">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              createCustomer();
            }}
            className="max-w-sm flex flex-col items-center justify-center gap-2 "
          >
            <label>Create Account</label>
            <input
              type="text"
              placeholder="Name"
              className="border border-neutral-200 p-2"
            />
            <button type="submit">Submit</button>
          </form>
        </section>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
